-- Initialize tables required by case-search and case-admin pages
-- Safe to run multiple times.

create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  issuing_place text,
  id_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.user_profiles add column if not exists issuing_place text;
alter table if exists public.user_profiles add column if not exists id_number text;

create table if not exists public.user_records (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '未命名案件',
  info_text text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.record_photos (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.user_records(id) on delete cascade,
  photo_url text not null,
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.record_messages (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.user_records(id) on delete cascade,
  sender_role text not null default 'staff',
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_records_auth_user_id on public.user_records(auth_user_id);
create index if not exists idx_record_photos_record_id on public.record_photos(record_id);
create index if not exists idx_record_messages_record_id on public.record_messages(record_id);

alter table public.user_profiles enable row level security;
alter table public.user_records enable row level security;
alter table public.record_photos enable row level security;
alter table public.record_messages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'profile_select_own'
  ) then
    create policy profile_select_own on public.user_profiles
      for select to authenticated
      using (auth.uid() = auth_user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'profile_upsert_own'
  ) then
    create policy profile_upsert_own on public.user_profiles
      for all to authenticated
      using (auth.uid() = auth_user_id)
      with check (auth.uid() = auth_user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_records' and policyname = 'records_select_own'
  ) then
    create policy records_select_own on public.user_records
      for select to authenticated
      using (auth.uid() = auth_user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_records' and policyname = 'records_modify_own'
  ) then
    create policy records_modify_own on public.user_records
      for all to authenticated
      using (auth.uid() = auth_user_id)
      with check (auth.uid() = auth_user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_photos' and policyname = 'photos_select_own'
  ) then
    create policy photos_select_own on public.record_photos
      for select to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_photos' and policyname = 'photos_modify_own'
  ) then
    create policy photos_modify_own on public.record_photos
      for all to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_messages' and policyname = 'messages_select_own'
  ) then
    create policy messages_select_own on public.record_messages
      for select to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_messages' and policyname = 'messages_modify_own'
  ) then
    create policy messages_modify_own on public.record_messages
      for all to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;
end
$$;
